name: Build and Deploy

on:
  push:
    branches:
      - main 
      - workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
    
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Merge with gh-pages
        run: |
          git checkout -b gh-pages

      - name: Clean and Copy Dist
        run: |
          rm -rf public/
          rm -rf src/
          rm index.html
          rm *.json
          rm *.js
          rm *.ts
          cp -r dist/* .

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Build'
          branch: gh-pages
